### ISSUE TITLE
Allow user to change avatar on /profile/edit

### ISSUE THREAD

**Issue by jonsimington** [jonsimington/clockwork.pw#1]
We have an avatar field now!

**Comment by ksoonn** [comment]
my avatar works with gravatar, but manually uploading in profile/edit does not update the avatar

**Comment by jonsimington** [comment]
Yup. The server isn't serving the uploaded avatars. I'll get this working soon



—

**Comment by jonsimington** [comment]
Speaking of which, I need to remove that avatar field

**Comment by jonsimington** [comment]
finally!

5a4d4da3456a520950a701aeb40d87fe18eacc94
