### ISSUE TITLE
Indicate author of post and last user to post for threads.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#16]
Under the title of the thread, have a line "by [user] on [timestamp]" or some variation of that. Under the "last post" column also have a similar indicator.

**Comment by jonsimington** [comment]
addressed by 3344df932bc49f549d52b2b1db2dbcff5b20c3dc

**Comment by ksoonn** [comment]
Would be nice to also have the original author of the post indicated without having to click into a thread to see who created the thread.

**Comment by jonsimington** [comment]
via b9e3762ca809186c9b7d342085cccb78e03012ac
