### ISSUE TITLE
Make the Guild Roster title separate from box and also add a title for forums pages for consistency across site.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#19]
Similar to the "blog" and "about us" pages. I think the "roster" page should have a title "Guild Roster" separate from the box. The forum home page can also have a persistent title, maybe "<Clockwork> Forums".

**Comment by jonsimington** [comment]
via 5b75038f3ae3334a155a81f6364a77b83e39d2a7
