### ISSUE TITLE
Change post entries' "Updated [timestamp]" to "Posted [timestamp]" as updated is misleading.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#38]

**Comment by ksoonn** [comment]
let me know what you think:
what if you had both "Posted [ts]" and "Updated [ts]" both at the top right?

for example:

"Posted [ts]" for unedited, then if edited
"Posted [ts], edited [ts]" maybe the "edited [ts]" can be emphasized in some way, or not, whatever looks better.

then you can just not have the "Edited [ts]" that shows up right below the content.

The font size might have to be reduced or maybe they have to be put on separate lines, I'm not really sure if it will get too long to look good.

**Comment by jonsimington** [comment]
via f6d4e4f152854cb6820345d3dc6bb40695578f85 and 0ca10b46a3265470911d5835ef76ba5d4b079ff9
