### ISSUE TITLE
Remove "Clockwork Forums" title, remove contrast box for the breadcrumbs.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#39]
I thought the title would look okay but I think doing without it might be better now (the large centered one on the home forum page). Also not sure how I feel about the contrast box for the breadcrumbs, but it might be nicer without it since the majority of it is empty and stretches across the top. (keep breadcrumbs, no shaded box)

think those changes would look better?

**Comment by jonsimington** [comment]
I think we need the gray for contrast, but I can make them labels so there is no wasted space

**Comment by ksoonn** [comment]
maybe, I was thinking something like this http://altered-time.com/forum/viewforum.php?f=5&sid=d2ae746cd491121ab22f44f9dba5a231

**Comment by jonsimington** [comment]
via 2f2bc9a139f4fbc2001da84a400d83f2fdbd1a49
