### ISSUE TITLE
Image size protection broken for Firefox browser.

### ISSUE THREAD

**Issue by jonsimington** [jonsimington/clockwork.pw#54]
Submitter: Roman
In line images.

Images should be resized to the width of the screen. Right now images can go out of bounds of a post.

Especially evident with people who haven't changed avatars yet.

example http://i.imgur.com/J4y7tOK.png

**Comment by ksoonn** [comment]
This seems to apply to avatars and in-line images for posts, and only to certain posts and avatars for some reason.

**Comment by jonsimington** [comment]
http://i.imgur.com/H2LsKC3.jpg
