### ISSUE TITLE
Add signature on forum

### ISSUE THREAD

**Issue by yuckypoo** [jonsimington/clockwork.pw#57]
Would be nice to add this functionality. Whatchoo think?

**Comment by jonsimington** [comment]
Its there!  I need to add it to the profile edit form!  I'll get on it



—

**Comment by yuckypoo** [comment]
oh ok cool. no rush just addin stuff that I can think of

**Comment by jonsimington** [comment]
2254ddb0d63e3b776407e301f94b74a5f635ee80
