### ISSUE TITLE
Remove "Comment:" text next to editbox and have a fixed width for editbox for comment section in applications.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#70]
Right now the editbox defaults to a small width that makes the page look weird. It is resizable but there is no limit on the width when dragged. I think it should just be a fixed width with the precursor text removed due to redundancy.

**Comment by jonsimington** [comment]
Working on stuff like that right now


—

**Comment by jonsimington** [comment]
fixed width does the trick

**Comment by jonsimington** [comment]
Can't seem to remove the "Comment:" text, but the box is bigger and looks better

7711255694a33d550ce7167f35d26bf6cfed3d99
