### ISSUE TITLE
Integrate main character/class/spec into user profile and have roster pull from that.

### ISSUE THREAD

**Issue by ksoonn** [jonsimington/clockwork.pw#91]
Not sure how important this is but when people switch toons/specs like Botti / Yucky, they can easily just update their main from their own profile.

**Comment by ksoonn** [comment]
or maybe just allow them to still edit their own app somehow, perhaps a link within their "edit profile" page.

**Comment by jonsimington** [comment]
This is turning out to be a pain to handle through the profile update form -- going to let members edit their applications, I guess
