### ISSUE TITLE
Media Page

### ISSUE THREAD

**Issue by yuckypoo** [jonsimington/clockwork.pw#97]
Add media page with several categories on left, loads content in middle. Images can be slideshow style click arrow on left or right or something to go to next pic, with thumbnails maybe on bottom? whatever is easiest for you.

Categories are:

Blackrock Foundry
- [Gruul](https://www.youtube.com/watch?v=K2_qSPU0FEM)
- [Oregorger](https://www.youtube.com/watch?v=LAyaetuIN2o)
- [Blast Furnace](https://www.youtube.com/watch?v=vibc6COEbPY)
- [Beastlord Darmac]()
- [Operator Thogar](https://www.youtube.com/watch?v=HbP4f8vZwwE)
- [Iron Maidens](https://www.youtube.com/watch?v=zqoy-cT9Vng)
- [Hans'gar and Franzok](https://www.youtube.com/watch?v=VTwkTneShdI)
- [Flamebender Ka'graz](https://www.youtube.com/watch?v=f5cNFQSJ-0w)
- [Kromog](https://www.youtube.com/watch?v=4oQEjdyNNh0)
- [Blackhand](https://www.youtube.com/watch?v=DpkEvBe57uc)

Highmaul
- [Mythic Tectus](https://www.youtube.com/watch?v=jJGJmOUiTe4)
- [Mythic Butcher](https://www.youtube.com/watch?v=k1_Nno35weI)
- [Mythic Twin Orgron](https://www.youtube.com/watch?v=bPwKXlubwcE)

Siege of Orgrimmar
- [Heroic Garrosh](https://www.youtube.com/watch?v=jMLFIuM627s)
- [Heroic Paragons of the Klaxxi](https://www.youtube.com/watch?v=m20YyrGpT9w)

Realm Best Challenge Modes
- [Gate of the Setting Sun](https://www.youtube.com/watch?v=CQ3d8OQH4Fo)
- [Stormstout Brewery]
- [Siege of Niuzao Temple](https://www.youtube.com/watch?v=fqHJd6HIrU4)

Funsies
- Boss Kill Screenshots
- Selfies
- [YATT Compilation](https://www.youtube.com/watch?v=fk90mnkhhPk)

Twitch
- [Adgetty (Warlock)](http://www.twitch.tv/adgetty)
- [Apparati (DPS Warrior)](http://www.twitch.tv/apparati)
- [Awss (Ret Pally)](http://www.twitch.tv/naughtycrusher)
- [Bottizelle (Resto Druid)](http://www.twitch.tv/bottizelle)
- [Qoof (Mage)](http://www.twitch.tv/qoofs)

**Comment by yuckypoo** [comment]
will i be able to update this or will you have to do it each time? for example removing some streams or adding new kill video.

**Comment by jonsimington** [comment]
I need to make it display multiple videos, first. I'll work on that today, then I'll teach you how to edit it



—

**Comment by jonsimington** [comment]
https://github.com/jonsimington/clockwork.pw/commit/5924fd050135643260154d02f6f02b97deaae3a1

message me later when you are available to learn how to edit it.

**Comment by jonsimington** [comment]
I like how it turned out.  Styling is still in the works.
